development:
  adapter: redis
  url: "redis://localhost:6379/1"
  channel_prefix: chesshq_development


test:
  adapter: test

production:
  adapter: redis
  url: "redis://localhost:6379/1"
  channel_prefix: chesshq_production
